"""empty message

Revision ID: 26286d563003
Revises: 
Create Date: 2023-05-13 23:11:16.429913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26286d563003'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('avaliado')
    op.drop_table('salto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('altura_salto', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('tempo_voo', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('forca_media', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('potencia_media', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('veloc_media', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('avaliado_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['avaliado_id'], ['avaliado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliado',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('sobrenome', sa.VARCHAR(), nullable=False),
    sa.Column('sexo', sa.VARCHAR(), nullable=False),
    sa.Column('peso', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('perna_flexionada', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('perna_estendida', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('senha', sa.VARCHAR(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('sobrenome', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
